# core/report_engine.py
"""
Professional Report Engine
موتور تولید گزارش‌های حرفه‌ای DDR, EOWR, NPT, Cost
"""
import os
import logging
from datetime import datetime, date
from typing import Dict, List, Any, Optional

from sqlalchemy import func

from PySide6.QtGui import QTextDocument, QPageSize, QPageLayout
from PySide6.QtCore import QMarginsF
from PySide6.QtPrintSupport import QPrinter

logger = logging.getLogger(__name__)

from core.text_utils import wrap_html, safe_str, fmt_num

class ReportBranding:
    """تنظیمات برندینگ سازمانی"""
    
    def __init__(self):
        self.company_name = "DrillMaster"
        self.logo_path = ""
        self.primary_color = "#2c3e50"
        self.secondary_color = "#3498db"
        self.accent_color = "#27ae60"
        self.header_bg = "#2c3e50"
        self.header_text = "#ffffff"
        self.watermark = ""  # Draft / Confidential / Final
        self.footer_text = "Generated by DrillMaster"
    
    def to_css(self):
        return f"""
        :root {{
            --primary: {self.primary_color};
            --secondary: {self.secondary_color};
            --accent: {self.accent_color};
            --header-bg: {self.header_bg};
            --header-text: {self.header_text};
        }}
        """


class DDRReportEngine:
    """موتور تولید DDR حرفه‌ای"""

    def __init__(self, db_manager):
        self.db = db_manager
        self.branding = ReportBranding()

    def generate(self, report_id: int, output_path: str,
                 format: str = "pdf") -> bool:
        """تولید DDR"""
        try:
            data = self._collect_data(report_id)
            if not data:
                logger.error("No data for DDR")
                return False

            html = self._build_html(data)

            if format == "pdf":
                return self._save_pdf(html, output_path)
            elif format == "html":
                return self._save_html(html, output_path)
            elif format == "excel":
                return self._save_excel(data, output_path)
            return False
        except Exception as e:
            logger.error(f"DDR generation error: {e}")
            return False

    def _collect_data(self, report_id: int) -> Optional[Dict]:
        """جمع‌آوری تمام داده‌های گزارش"""
        report = self.db.get_daily_report_by_id(report_id)
        if not report:
            return None

        well_id = report.get("well_id")
        well = self.db.get_well_by_id(well_id) or {}

        # Header snapshot اگر وجود دارد
        snapshot = report.get("header_snapshot") or {}

        # Time logs
        from core.database import TimeLog24H, TimeLogMorning
        session = self.db.create_session()
        try:
            logs_24h = session.query(TimeLog24H).filter(
                TimeLog24H.report_id == report_id
            ).order_by(TimeLog24H.time_from).all()

            logs_morning = session.query(TimeLogMorning).filter(
                TimeLogMorning.report_id == report_id
            ).order_by(TimeLogMorning.time_from).all()
        finally:
            session.close()

        # Drilling params
        params = self.db.get_drilling_parameters(report_id=report_id)

        # Mud report
        mud = self.db.get_mud_report(report_id=report_id)

        # Sections
        sections = self.db.get_sections_by_well(well_id)
        current_section = None
        if report.get("section_id"):
            current_section = next(
                (s for s in sections if s["id"] == report["section_id"]),
                None
            )

        # Time analysis
        total_hrs = sum(l.duration or 0 for l in logs_24h)
        npt_hrs = sum(
            l.duration or 0 for l in logs_24h if l.is_npt
        )
        pt_hrs = total_hrs - npt_hrs

        return {
            "report": report,
            "well": well,
            "snapshot": snapshot,
            "logs_24h": logs_24h,
            "logs_morning": logs_morning,
            "params": params,
            "mud": mud,
            "section": current_section,
            "total_hrs": total_hrs,
            "npt_hrs": npt_hrs,
            "pt_hrs": pt_hrs,
        }

    def _build_html(self, data: Dict) -> str:
        """ساخت HTML حرفه‌ای DDR"""
        r = data["report"]
        w = data["well"]
        snap = data["snapshot"]
        params = data["params"] or {}
        mud = data["mud"] or {}

        def fmt_num(value, digits=1, default=0):
            """فرمت امن برای مقادیر عددی"""
            try:
                if value is None or value == "":
                    value = default
                return f"{float(value):.{digits}f}"
            except (ValueError, TypeError):
                return f"{float(default):.{digits}f}"

        def safe_str(value, default=""):
            """رشته امن"""
            if value is None:
                return default
            return str(value)
            
        section = data["section"] or {}
        logs_24 = data["logs_24h"]
        logs_m = data["logs_morning"]
        total = data["total_hrs"]
        npt = data["npt_hrs"]
        pt = data["pt_hrs"]

        # اطلاعات هدر (اول snapshot بعد well)
        def h(key, fallback_key=None):
            v = snap.get(key)
            if v:
                return str(v)
            if fallback_key:
                return str(w.get(fallback_key, "") or "")
            return str(w.get(key, "") or "")

        well_name = h("well_name", "name")
        rig_name = h("rig_name")
        operator = h("operator")
        client = h("client")
        field_name = h("field_name")
        contractor = h("drilling_contractor")
        sup_day = h("supervisor_day")
        sup_night = h("supervisor_night")
        geologist = h("geologist1")
        toolpusher = h("tool_pusher_day")
        formation = h("formation")
        section_name = section.get("name", h("section_name"))

        rd = safe_str(r.get("report_date", ""))
        rno = safe_str(r.get("report_number", ""))
        rig_day = safe_str(r.get("rig_day", ""))
        d0 = float(r.get("depth_0000") or 0)
        d6 = float(r.get("depth_0600") or 0)
        d24 = float(r.get("depth_2400") or 0)
        progress = d24 - d0
        summary = safe_str(r.get("summary", ""), "")
        status = safe_str(r.get("status", "Draft"), "Draft")

        bc = self.branding

        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
@page {{ margin: 2mm; size: A4; }}
body {{ 
    font-family: Arial, Helvetica, sans-serif; 
    font-size: 8pt; 
    color: #2c3e50; 
    margin: 0; padding: 2mm;
    width: 206mm;
    max-width: 206mm;
}}

/* همه جداول محدود به عرض صفحه */
table {{
    width: 100% !important;
    max-width: 190mm !important;
    table-layout: fixed !important;
    word-wrap: break-word !important;
    overflow-wrap: break-word !important;
}}

.report-header {{
    background: {bc.header_bg};
    color: {bc.header_text};
    padding: 8px 10px;
    border-radius: 3px;
    margin-bottom: 6px;
}}
.report-header h1 {{
    margin: 0; font-size: 14pt; letter-spacing: 1px;
}}
.report-header .subtitle {{
    font-size: 8pt; opacity: 0.8; margin-top: 2px;
}}

.info-grid {{
    width: 100%; border-collapse: collapse; 
    margin-bottom: 6px; font-size: 7.5pt;
    table-layout: fixed;
}}
.info-grid td {{
    padding: 3px 4px; border: 1px solid #bdc3c7;
    word-wrap: break-word;
    overflow: hidden;
}}
.info-grid .label {{
    background: #ecf0f1; font-weight: bold; 
    color: {bc.primary_color}; width: 11%;
    white-space: nowrap;
    font-size: 7pt;
}}
.info-grid .value {{
    width: 14%;
    font-size: 7.5pt;
}}

.section-title {{
    background: {bc.secondary_color};
    color: white; padding: 4px 8px;
    font-weight: bold; font-size: 9pt;
    border-radius: 2px; margin: 6px 0 3px 0;
}}

.data-table {{
    width: 100%; border-collapse: collapse; 
    margin-bottom: 6px; font-size: 7pt;
    table-layout: fixed;
}}
.data-table th {{
    background: {bc.primary_color}; color: white;
    padding: 3px 4px; text-align: left;
    font-size: 6.5pt;
    word-wrap: break-word;
}}
.data-table td {{
    padding: 2px 3px; border: 1px solid #bdc3c7;
    vertical-align: top;
    word-wrap: break-word;
    overflow-wrap: break-word;
    max-width: 0;
}}
.data-table tr:nth-child(even) {{
    background: #f8f9fa;
}}
.data-table .npt-row {{
    background: #fadbd8 !important;
}}

/* Description column عریض‌تر */
.data-table td:last-child {{
    width: 40%;
}}

.summary-box {{
    background: #f8f9fa; border: 1px solid #dee2e6;
    border-radius: 3px; padding: 6px 8px;
    margin: 4px 0; font-size: 7.5pt;
    line-height: 1.3;
    word-wrap: break-word;
}}

.time-bar {{
    height: 14px; border-radius: 7px;
    overflow: hidden; background: #ecf0f1;
    margin: 3px 0;
}}
.time-bar-pt {{ height: 100%; background: {bc.accent_color}; float: left; }}
.time-bar-npt {{ height: 100%; background: #e74c3c; float: left; }}

.footer {{
    margin-top: 8px; padding-top: 4px;
    border-top: 2px solid {bc.primary_color};
    font-size: 6pt; color: #999;
    text-align: center;
}}

.watermark {{
    position: fixed; top: 40%; left: 20%;
    font-size: 50pt; color: rgba(0,0,0,0.03);
    transform: rotate(-30deg); z-index: -1;
}}
</style></head>
<body>"""

        # Watermark
        if bc.watermark:
            html += f'<div class="watermark">{bc.watermark}</div>'

        # Header
        html += f"""
<div class="report-header">
    <h1>📋 DAILY DRILLING REPORT</h1>
    <div class="subtitle">{bc.company_name} | {well_name} | Report #{rno} | {rd}</div>
</div>"""

        # Well Info Grid
        html += f"""
<table class="info-grid">
<tr>
    <td class="label">Well</td><td class="value">{well_name}</td>
    <td class="label">Rig</td><td class="value">{rig_name}</td>
    <td class="label">Report #</td><td class="value">{rno}</td>
    <td class="label">Rig Day</td><td class="value">{rig_day}</td>
</tr>
<tr>
    <td class="label">Operator</td><td class="value">{operator}</td>
    <td class="label">Client</td><td class="value">{client}</td>
    <td class="label">Field</td><td class="value">{field_name}</td>
    <td class="label">Date</td><td class="value">{rd}</td>
</tr>
<tr>
    <td class="label">Contractor</td><td class="value">{contractor}</td>
    <td class="label">Section</td><td class="value">{section_name}</td>
    <td class="label">Formation</td><td class="value">{formation}</td>
    <td class="label">Status</td><td class="value">{status}</td>
</tr>
<tr>
    <td class="label">Sup. Day</td><td class="value">{sup_day}</td>
    <td class="label">Sup. Night</td><td class="value">{sup_night}</td>
    <td class="label">Geologist</td><td class="value">{geologist}</td>
    <td class="label">Toolpusher</td><td class="value">{toolpusher}</td>
</tr>
</table>"""

        # Depth Summary
        html += f"""
<div class="section-title">📏 Depth Summary</div>
<table class="info-grid">
<tr>
    <td class="label">@ 00:00</td><td class="value"><b>{d0:.1f}</b> m</td>
    <td class="label">@ 06:00</td><td class="value"><b>{d6:.1f}</b> m</td>
    <td class="label">@ 24:00</td><td class="value"><b>{d24:.1f}</b> m</td>
    <td class="label">Progress</td><td class="value" style="color:{bc.accent_color};font-weight:bold">{progress:.1f} m</td>
</tr>
</table>"""

        # Drilling Parameters
        if params:
            html += f"""
<div class="section-title">⚙️ Drilling Parameters</div>
<table class="info-grid">
<tr>
    <td class="label">Bit #</td><td class="value">{safe_str(params.get('bit_no',''))}</td>
    <td class="label">Size</td><td class="value">{safe_str(params.get('bit_size',''))}"</td>
    <td class="label">Type</td><td class="value">{safe_str(params.get('bit_type',''))}</td>
    <td class="label">ROP</td><td class="value"><b>{fmt_num(params.get('avg_rop'), 1)}</b> m/hr</td>
</tr>
<tr>
    <td class="label">WOB</td><td class="value">{safe_str(params.get('wob_min',0))}-{safe_str(params.get('wob_max',0))} klb</td>
    <td class="label">RPM</td><td class="value">{safe_str(params.get('rpm_min',0))}-{safe_str(params.get('rpm_max',0))}</td>
    <td class="label">Torque</td><td class="value">{safe_str(params.get('torque_min',0))}-{safe_str(params.get('torque_max',0))} klb.ft</td>
    <td class="label">SPP</td><td class="value">{safe_str(params.get('pump_pressure_min',0))}-{safe_str(params.get('pump_pressure_max',0))} psi</td>
</tr>
</table>"""

        # Mud Report
        if mud:
            html += f"""
<div class="section-title">🧪 Mud Properties</div>
<table class="info-grid">
<tr>
    <td class="label">Type</td><td class="value">{safe_str(mud.get('mud_type',''))}</td>
    <td class="label">MW</td><td class="value"><b>{fmt_num(mud.get('mw'), 1)}</b> pcf</td>
    <td class="label">PV</td><td class="value">{fmt_num(mud.get('pv'), 1)} cp</td>
    <td class="label">YP</td><td class="value">{fmt_num(mud.get('yp'), 1)}</td>
</tr>
<tr>
    <td class="label">Gel 10s/10m</td><td class="value">{fmt_num(mud.get('gel_10s'),1)}/{fmt_num(mud.get('gel_10m'),1)}</td>
    <td class="label">FL</td><td class="value">{fmt_num(mud.get('fl'),1)}</td>
    <td class="label">pH</td><td class="value">{fmt_num(mud.get('ph'),1)}</td>
    <td class="label">Cl⁻</td><td class="value">{fmt_num(mud.get('chloride'),0)} ppm</td>
</tr>
<tr>
    <td class="label">Temp</td><td class="value">{fmt_num(mud.get('temperature'),1)} °C</td>
    <td class="label">Solids</td><td class="value">{fmt_num(mud.get('solid_percent'),1)}%</td>
    <td class="label">Vol Hole</td><td class="value">{fmt_num(mud.get('volume_hole'),1)} bbl</td>
    <td class="label">Loss DH</td><td class="value">{fmt_num(mud.get('loss_downhole'),1)} bbl</td>
</tr>
</table>"""

        # 24h Operations
        html += f"""
<div class="section-title">🕒 24-Hour Operations</div>
<table class="data-table">
<tr>
    <th style="width:6%">From</th>
    <th style="width:6%">To</th>
    <th style="width:5%">Hrs</th>
    <th style="width:10%">Phase</th>
    <th style="width:13%">Code</th>
    <th style="width:4%">NPT</th>
    <th style="width:56%">Description</th>
</tr>"""

        for log in logs_24:
            tf = log.time_from.strftime("%H:%M") if log.time_from else ""
            tt = log.time_to.strftime("%H:%M") if log.time_to else ""
            cls = ' class="npt-row"' if log.is_npt else ""
            npt_mark = "⚠️" if log.is_npt else ""
            import textwrap
            desc = log.activity_description or ""
            desc_html = wrap_html(desc)

            html += f"""<tr{cls}>
    <td>{tf}</td><td>{tt}</td>
    <td style="text-align:right">{fmt_num(log.duration, 2)}</td>
    <td>{safe_str(log.main_phase)}</td>
    <td>{safe_str(log.main_code)}</td>
    <td style="text-align:center">{npt_mark}</td>
    <td>{desc_html}</td>
</tr>"""

        html += "</table>"

        # Morning Tour
        if logs_m:
            html += f"""
<div class="section-title">☀️ Morning Tour</div>
<table class="data-table">
<tr>
    <th style="width:6%">From</th>
    <th style="width:6%">To</th>
    <th style="width:5%">Hrs</th>
    <th style="width:13%">Code</th>
    <th style="width:70%">Description</th>
</tr>"""
            for log in logs_m:
                tf = log.time_from.strftime("%H:%M") if log.time_from else ""
                tt = log.time_to.strftime("%H:%M") if log.time_to else ""
                html += f"""<tr>
    <td>{tf}</td><td>{tt}</td>
    <td style="text-align:right">{fmt_num(log.duration, 2)}</td>
    <td>{safe_str(log.main_code)}</td>
    <td>{wrap_html(log.activity_description)}</td>
</tr>"""
            html += "</table>"

        # Time Analysis
        pt_pct = (pt / total * 100) if total > 0 else 100
        npt_pct = (npt / total * 100) if total > 0 else 0

        html += f"""
<div class="section-title">📊 Time Analysis</div>
<table class="info-grid">
<tr>
    <td class="label">Total Hours</td>
    <td class="value"><b>{total:.1f}</b></td>
    <td class="label">Productive</td>
    <td class="value" style="color:{bc.accent_color}"><b>{pt:.1f}</b> ({pt_pct:.0f}%)</td>
    <td class="label">NPT</td>
    <td class="value" style="color:#e74c3c"><b>{npt:.1f}</b> ({npt_pct:.0f}%)</td>
    <td class="label">Efficiency</td>
    <td class="value"><b>{pt_pct:.0f}%</b></td>
</tr>
</table>
<div class="time-bar">
    <div class="time-bar-pt" style="width:{pt_pct:.0f}%"></div>
    <div class="time-bar-npt" style="width:{npt_pct:.0f}%"></div>
</div>"""

        # Summary
        if summary:
            html += f"""
<div class="section-title">📝 Operations Summary</div>
<div class="summary-box">{wrap_html(summary)}</div>"""

        # Footer
        html += f"""
<div class="footer">
    {bc.footer_text} | {datetime.now().strftime('%Y-%m-%d %H:%M')} | 
    Well: {well_name} | Report #{rno} | Page 1
</div>
</body></html>"""

        return html

    def _save_pdf(self, html: str, output_path: str) -> bool:
        try:
            printer = QPrinter(QPrinter.HighResolution)
            printer.setOutputFormat(QPrinter.PdfFormat)
            printer.setOutputFileName(output_path)
            printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
            printer.setPageMargins(
                QMarginsF(2, 2, 2, 2),
                QPageLayout.Unit.Millimeter
            )

            doc = QTextDocument()
            doc.setHtml(html)
            doc.print_(printer)

            logger.info(f"PDF saved: {output_path}")
            return True
        except Exception as e:
            logger.error(f"PDF save error: {e}")
            return False

    def _save_html(self, html: str, output_path: str) -> bool:
        """ذخیره HTML"""
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html)
            return True
        except Exception as e:
            logger.error(f"HTML save error: {e}")
            return False

    def _save_excel(self, data: Dict, output_path: str) -> bool:
        """ذخیره Excel"""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill, Alignment

            wb = Workbook()

            # Sheet 1: Report Header
            ws1 = wb.active
            ws1.title = "DDR Header"
            header_font = Font(bold=True, color="FFFFFF")
            header_fill = PatternFill("solid", fgColor="2C3E50")

            r = data["report"]
            w = data["well"]
            rows = [
                ("Field", "Value"),
                ("Well Name", w.get("name", "")),
                ("Report #", r.get("report_number", "")),
                ("Date", str(r.get("report_date", ""))),
                ("Rig Day", r.get("rig_day", "")),
                ("Depth 00:00", r.get("depth_0000", 0)),
                ("Depth 06:00", r.get("depth_0600", 0)),
                ("Depth 24:00", r.get("depth_2400", 0)),
                ("Status", r.get("status", "")),
                ("Summary", r.get("summary", "")),
            ]
            for i, (k, v) in enumerate(rows):
                ws1.cell(row=i+1, column=1, value=k)
                ws1.cell(row=i+1, column=2, value=str(v))
                if i == 0:
                    ws1.cell(row=1, column=1).font = header_font
                    ws1.cell(row=1, column=1).fill = header_fill
                    ws1.cell(row=1, column=2).font = header_font
                    ws1.cell(row=1, column=2).fill = header_fill

            # Sheet 2: Time Logs
            ws2 = wb.create_sheet("24h Time Log")
            headers = ["From", "To", "Duration", "Phase", "Code",
                        "Sub Code", "NPT", "Description"]
            for c, h in enumerate(headers, 1):
                cell = ws2.cell(row=1, column=c, value=h)
                cell.font = header_font
                cell.fill = header_fill

            for i, log in enumerate(data["logs_24h"], 2):
                tf = log.time_from.strftime("%H:%M") if log.time_from else ""
                tt = log.time_to.strftime("%H:%M") if log.time_to else ""
                ws2.cell(row=i, column=1, value=tf)
                ws2.cell(row=i, column=2, value=tt)
                ws2.cell(row=i, column=3, value=log.duration or 0)
                ws2.cell(row=i, column=4, value=log.main_phase or "")
                ws2.cell(row=i, column=5, value=log.main_code or "")
                ws2.cell(row=i, column=6, value=log.sub_code or "")
                ws2.cell(row=i, column=7, value="Yes" if log.is_npt else "")
                ws2.cell(row=i, column=8, value=log.activity_description or "")

            # Sheet 3: Drilling Params
            if data["params"]:
                ws3 = wb.create_sheet("Drilling Params")
                p = data["params"]
                param_rows = [
                    ("Parameter", "Value"),
                    ("Bit No", p.get("bit_no", "")),
                    ("Bit Size", p.get("bit_size", "")),
                    ("Bit Type", p.get("bit_type", "")),
                    ("Avg ROP", p.get("avg_rop", 0)),
                    ("WOB Min-Max", f"{p.get('wob_min',0)}-{p.get('wob_max',0)}"),
                    ("RPM Min-Max", f"{p.get('rpm_min',0)}-{p.get('rpm_max',0)}"),
                ]
                for i, (k, v) in enumerate(param_rows):
                    ws3.cell(row=i+1, column=1, value=k)
                    ws3.cell(row=i+1, column=2, value=str(v))

            # Sheet 4: Mud
            if data["mud"]:
                ws4 = wb.create_sheet("Mud Report")
                m = data["mud"]
                mud_rows = [
                    ("Property", "Value"),
                    ("Mud Type", m.get("mud_type", "")),
                    ("MW (pcf)", m.get("mw", 0)),
                    ("PV (cp)", m.get("pv", 0)),
                    ("YP", m.get("yp", 0)),
                    ("pH", m.get("ph", 0)),
                    ("FL", m.get("fl", 0)),
                    ("Chloride", m.get("chloride", 0)),
                ]
                for i, (k, v) in enumerate(mud_rows):
                    ws4.cell(row=i+1, column=1, value=k)
                    ws4.cell(row=i+1, column=2, value=str(v))

            wb.save(output_path)
            return True
        except Exception as e:
            logger.error(f"Excel save error: {e}")
            return False

class EOWRReportEngine:
    """موتور تولید End of Well Report حرفه‌ای"""

    def __init__(self, db_manager):
        self.db = db_manager
        self.branding = ReportBranding()

    def generate(self, well_id: int, output_path: str,
                 format: str = "pdf") -> bool:
        try:
            data = self._collect_data(well_id)
            if not data:
                logger.warning(
                    f"No plan data for well {well_id}"
                )
                return False

            # ✅ اگر plan نداشته باشد
            if not data.get("plan"):
                logger.warning(
                    f"No active plan for well {well_id}"
                )
                return False

            html = self._build_html(data, selected_sections=None)

            if format == "pdf":
                return self._save_pdf(html, output_path)
            elif format == "html":
                return self._save_html(html, output_path)
            elif format == "excel":
                return self._save_excel(data, output_path, selected_sections=None)
            return False
        except Exception as e:
            logger.error(f"EOWR report error: {e}", exc_info=True)
            return False

    def _collect_data(self, well_id: int) -> dict:
        """جمع‌آوری کامل داده‌های یک چاه برای EOWR"""
        from core.database import (
            DailyReport, DrillingParameters, MudReport, BitReport,
            BHAReport, SurveyPoint, CementReport, CasingReport,
            SafetyReport, TimeLog24H, TimeLogMorning,
            LogisticsPersonnel, ServiceCompany, TransportLog,
            MaterialRequest, EquipmentLog, Section
        )
        try:
            session = self.db.create_session()
            try:
                well = self.db.get_well_by_id(well_id) or {}
                sections = self.db.get_sections_by_well(well_id) or []

                daily_reports = session.query(DailyReport).filter(
                    DailyReport.well_id == well_id
                ).order_by(DailyReport.report_date).all()

                drilling_params = session.query(DrillingParameters).filter(
                    DrillingParameters.well_id == well_id
                ).order_by(DrillingParameters.report_date).all()

                mud_reports = session.query(MudReport).filter(
                    MudReport.well_id == well_id
                ).order_by(MudReport.report_date).all()

                bit_reports = session.query(BitReport).filter(
                    BitReport.well_id == well_id
                ).order_by(BitReport.report_date).all()

                bha_reports = session.query(BHAReport).filter(
                    BHAReport.well_id == well_id
                ).order_by(BHAReport.updated_at.desc()).all()

                surveys = session.query(SurveyPoint).filter(
                    SurveyPoint.well_id == well_id
                ).order_by(SurveyPoint.md).all()

                cement_reports = session.query(CementReport).filter(
                    CementReport.well_id == well_id
                ).order_by(CementReport.report_date).all()

                casing_reports = session.query(CasingReport).filter(
                    CasingReport.well_id == well_id
                ).order_by(CasingReport.report_date).all()

                safety_reports = session.query(SafetyReport).filter(
                    SafetyReport.well_id == well_id
                ).order_by(SafetyReport.report_date).all()

                time_logs_24h = session.query(TimeLog24H).join(
                    DailyReport, TimeLog24H.report_id == DailyReport.id
                ).filter(DailyReport.well_id == well_id).all()

                time_logs_morning = session.query(TimeLogMorning).join(
                    DailyReport, TimeLogMorning.report_id == DailyReport.id
                ).filter(DailyReport.well_id == well_id).all()

                personnel = session.query(LogisticsPersonnel).filter(
                    LogisticsPersonnel.well_id == well_id
                ).all()

                services = session.query(ServiceCompany).filter(
                    ServiceCompany.well_id == well_id
                ).all()

                transport = session.query(TransportLog).filter(
                    TransportLog.well_id == well_id
                ).all()

                requests = session.query(MaterialRequest).filter(
                    MaterialRequest.well_id == well_id
                ).all()

                equipment_logs = session.query(EquipmentLog).filter(
                    EquipmentLog.well_id == well_id
                ).all()

                # Cost records اگر وجود داشته باشد
                try:
                    from core.database import CostRecord
                    cost_records = session.query(CostRecord).filter(
                        CostRecord.well_id == well_id
                    ).all()
                except Exception:
                    cost_records = []

                # Derived summaries
                total_reports = len(daily_reports)
                final_depth = max(
                    [(r.depth_2400 or 0) for r in daily_reports],
                    default=0
                )
                total_npt = sum(
                    [(l.duration or 0) for l in time_logs_24h if l.is_npt]
                )
                total_hours = sum(
                    [(l.duration or 0) for l in time_logs_24h]
                ) or 1
                npt_pct = total_npt / total_hours * 100

                avg_rop = 0
                rops = [p.avg_rop for p in drilling_params if p.avg_rop]
                if rops:
                    avg_rop = sum(rops) / len(rops)

                total_cost = 0
                if cost_records:
                    total_cost = sum([(c.actual_cost or 0) for c in cost_records])
                else:
                    # fallback تخمینی
                    total_cost = total_reports * 60000

                return {
                    "well": well,
                    "sections": sections,
                    "daily_reports": daily_reports,
                    "drilling_params": drilling_params,
                    "mud_reports": mud_reports,
                    "bit_reports": bit_reports,
                    "bha_reports": bha_reports,
                    "surveys": surveys,
                    "cement_reports": cement_reports,
                    "casing_reports": casing_reports,
                    "safety_reports": safety_reports,
                    "time_logs_24h": time_logs_24h,
                    "time_logs_morning": time_logs_morning,
                    "personnel": personnel,
                    "services": services,
                    "transport": transport,
                    "requests": requests,
                    "equipment_logs": equipment_logs,
                    "cost_records": cost_records,
                    "summary": {
                        "total_reports": total_reports,
                        "final_depth": final_depth,
                        "avg_rop": avg_rop,
                        "total_npt": total_npt,
                        "npt_pct": npt_pct,
                        "total_cost": total_cost,
                    }
                }
            finally:
                session.close()
        except Exception as e:
            logger.error(f"EOWR collect data error: {e}")
            return {}

    def _build_html(self, data: dict, selected_sections=None) -> str:
        """ساخت HTML حرفه‌ای EOWR"""
        w = data.get("well", {})
        s = data.get("summary", {})
        bc = self.branding

        if not s:
            s = {}
        s.setdefault("total_reports", 0)
        s.setdefault("final_depth", 0)
        s.setdefault("avg_rop", 0)
        s.setdefault("total_npt", 0)
        s.setdefault("npt_pct", 0)
        s.setdefault("total_cost", 0)
        
        well_name = w.get("name", "Unknown Well")
        rig_name = w.get("rig_name", "")
        operator = w.get("operator", "")
        field_name = w.get("field_name", "")
        contractor = w.get("drilling_contractor", "")
        client = w.get("client", "")

        daily_reports = data.get("daily_reports", [])
        drilling_params = data.get("drilling_params", [])
        mud_reports = data.get("mud_reports", [])
        bit_reports = data.get("bit_reports", [])
        surveys = data.get("surveys", [])
        sections = data.get("sections", [])
        cement_reports = data.get("cement_reports", [])
        casing_reports = data.get("casing_reports", [])
        safety_reports = data.get("safety_reports", [])
        services = data.get("services", [])
        personnel = data.get("personnel", [])
        cost_records = data.get("cost_records", [])

        html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
@page {{ margin: 15mm; }}
body {{
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    color: #2c3e50;
    margin: 0;
    padding: 0;
}}
h1 {{
    color: {bc.primary_color};
    border-bottom: 3px solid {bc.secondary_color};
    padding-bottom: 8px;
    font-size: 18pt;
}}
h2 {{
    color: {bc.secondary_color};
    border-bottom: 1px solid #bdc3c7;
    padding-bottom: 4px;
    margin-top: 18px;
    font-size: 13pt;
}}
h3 {{
    color: {bc.primary_color};
    margin-top: 10px;
    font-size: 11pt;
}}
.cover {{
    text-align: center;
    padding-top: 100px;
    page-break-after: always;
}}
.cover .title {{
    font-size: 26pt;
    font-weight: bold;
    color: {bc.primary_color};
}}
.cover .subtitle {{
    font-size: 14pt;
    color: {bc.secondary_color};
    margin-top: 10px;
}}
.cover .meta {{
    margin-top: 50px;
    font-size: 11pt;
}}
.kpi-box {{
    display: inline-block;
    width: 22%;
    margin: 5px;
    background: #f8f9fa;
    border-left: 4px solid {bc.secondary_color};
    border-radius: 4px;
    padding: 10px;
    vertical-align: top;
}}
.kpi-value {{
    font-size: 18pt;
    font-weight: bold;
    color: {bc.primary_color};
}}
.kpi-label {{
    font-size: 8pt;
    color: #666;
}}
.table {{
    width: 100%;
    border-collapse: collapse;
    margin: 8px 0;
    font-size: 8pt;
}}
.table th {{
    background: {bc.primary_color};
    color: white;
    padding: 5px;
    border: 1px solid #ccc;
}}
.table td {{
    padding: 4px 5px;
    border: 1px solid #ddd;
    vertical-align: top;
}}
.table tr:nth-child(even) {{
    background: #f8f9fa;
}}
.note {{
    background: #fef9e7;
    border-left: 4px solid #f39c12;
    padding: 8px;
    border-radius: 4px;
    margin: 8px 0;
}}
.footer {{
    margin-top: 20px;
    font-size: 7pt;
    color: #999;
    text-align: center;
    border-top: 1px solid #ccc;
    padding-top: 5px;
}}
.page-break {{
    page-break-before: always;
}}
</style>
</head>
<body>
<div class="cover">
    <div class="title">END OF WELL REPORT</div>
    <div class="subtitle">{well_name}</div>
    <div class="meta">
        <p><b>Field:</b> {field_name}</p>
        <p><b>Operator:</b> {operator}</p>
        <p><b>Client:</b> {client}</p>
        <p><b>Rig:</b> {rig_name}</p>
        <p><b>Contractor:</b> {contractor}</p>
        <p><b>Generated:</b> {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
    </div>
</div>
"""

        # Executive Summary
        html += f"""
<h1>1. Executive Summary</h1>
<div>
    <div class="kpi-box">
        <div class="kpi-value">{s.get("total_reports", 0)}</div>
        <div class="kpi-label">Rig Days / Reports</div>
    </div>
    <div class="kpi-box">
        <div class="kpi-value">{s.get("final_depth", 0):.0f} m</div>
        <div class="kpi-label">Final Depth</div>
    </div>
    <div class="kpi-box">
        <div class="kpi-value">{s.get("avg_rop", 0):.1f}</div>
        <div class="kpi-label">Average ROP (m/hr)</div>
    </div>
    <div class="kpi-box">
        <div class="kpi-value">{s.get("total_npt", 0):.1f} h</div>
        <div class="kpi-label">Total NPT ({s.get("npt_pct", 0):.1f}%)</div>
    </div>
</div>
<div class="note">
<b>Total Estimated Cost:</b> ${s.get("total_cost", 0):,.0f}
</div>
"""

        # Well Info
        html += f"""
<h1>2. Well Information</h1>
<table class="table">
<tr><th>Field</th><th>Value</th><th>Field</th><th>Value</th></tr>
<tr><td>Well Name</td><td>{well_name}</td><td>Well Code</td><td>{w.get('code','')}</td></tr>
<tr><td>Well Type</td><td>{w.get('well_type','')}</td><td>Well Shape</td><td>{w.get('well_shape','')}</td></tr>
<tr><td>Target Depth</td><td>{w.get('target_depth',0)} m</td><td>Water Depth</td><td>{w.get('water_depth',0)} m</td></tr>
<tr><td>Spud Date</td><td>{w.get('spud_date','')}</td><td>Formation</td><td>{w.get('formation','')}</td></tr>
<tr><td>Supervisor Day</td><td>{w.get('supervisor_day','')}</td><td>Supervisor Night</td><td>{w.get('supervisor_night','')}</td></tr>
<tr><td>Geologist</td><td>{w.get('geologist1','')}</td><td>Toolpusher</td><td>{w.get('tool_pusher_day','')}</td></tr>
</table>
"""

        # Sections
        html += "<h1>3. Section Summary</h1>"
        if sections:
            html += """<table class="table">
<tr><th>Name</th><th>Code</th><th>Depth From</th><th>Depth To</th><th>Hole Size</th><th>Purpose</th></tr>"""
            for sec in sections:
                html += f"""<tr>
<td>{sec.get('name','')}</td>
<td>{sec.get('code','')}</td>
<td>{sec.get('depth_from',0)}</td>
<td>{sec.get('depth_to',0)}</td>
<td>{sec.get('hole_size',0)}</td>
<td>{sec.get('purpose','')}</td>
</tr>"""
            html += "</table>"
        else:
            html += "<p>No section data available.</p>"

        # Daily Reports
        html += '<div class="page-break"></div><h1>4. Daily Reports Summary</h1>'
        if daily_reports:
            html += """<table class="table">
<tr><th>Date</th><th>Report #</th><th>Rig Day</th><th>Depth 24:00</th><th>Progress</th><th>Status</th><th>Summary</th></tr>"""
            for r in daily_reports:
                d0 = r.depth_0000 or 0
                d24 = r.depth_2400 or 0
                progress = d24 - d0
                summary = wrap_html((r.summary or ""), 150)
                html += f"""<tr>
<td>{r.report_date}</td>
<td>{r.report_number}</td>
<td>{r.rig_day}</td>
<td>{d24:.1f}</td>
<td>{progress:.1f}</td>
<td>{r.status}</td>
<td>{summary}</td>
</tr>"""
            html += "</table>"

        # Drilling Performance
        html += '<div class="page-break"></div><h1>5. Drilling Performance</h1>'
        if drilling_params:
            html += """<table class="table">
<tr><th>Date</th><th>Bit No</th><th>Bit Size</th><th>Depth In</th><th>Depth Out</th><th>Bit Drilled</th><th>ROP</th><th>WOB Max</th><th>RPM Max</th><th>SPP Max</th></tr>"""
            for p in drilling_params:
                html += f"""<tr>
<td>{p.report_date}</td>
<td>{p.bit_no or ''}</td>
<td>{p.bit_size or ''}</td>
<td>{p.depth_in or 0}</td>
<td>{p.depth_out or 0}</td>
<td>{p.bit_drilled or 0}</td>
<td>{p.avg_rop or 0:.1f}</td>
<td>{p.wob_max or 0}</td>
<td>{p.rpm_max or 0}</td>
<td>{p.pump_pressure_max or 0}</td>
</tr>"""
            html += "</table>"

        # Mud Summary
        html += "<h1>6. Mud Summary</h1>"
        if mud_reports:
            html += """<table class="table">
<tr><th>Date</th><th>Type</th><th>MW</th><th>PV</th><th>YP</th><th>FL</th><th>pH</th><th>Temp</th><th>Loss DH</th></tr>"""
            for m in mud_reports:
                html += f"""<tr>
<td>{m.report_date}</td>
<td>{m.mud_type or ''}</td>
<td>{m.mw or 0:.1f}</td>
<td>{m.pv or 0:.1f}</td>
<td>{m.yp or 0:.1f}</td>
<td>{m.fl or 0:.1f}</td>
<td>{m.ph or 0:.1f}</td>
<td>{m.temperature or 0:.1f}</td>
<td>{m.loss_downhole or 0:.1f}</td>
</tr>"""
            html += "</table>"

        # Cement / Casing
        html += "<h1>7. Casing & Cementing</h1>"
        html += f"<p><b>Cement Reports:</b> {len(cement_reports)} | <b>Casing Reports:</b> {len(casing_reports)}</p>"

        # Survey
        html += "<h1>8. Trajectory / Survey</h1>"
        if surveys:
            last = surveys[-1]
            html += f"""
<div class="note">
<b>Final Survey:</b><br>
MD: {last.md:.2f} m | TVD: {last.tvd:.2f} m | North: {last.north:.2f} m |
East: {last.east:.2f} m | HD: {last.hd:.2f} m | DLS: {last.dls:.2f}
</div>
"""
            html += """<table class="table">
<tr><th>MD</th><th>Inc</th><th>Azi</th><th>TVD</th><th>North</th><th>East</th><th>DLS</th></tr>"""
            for srow in surveys[:100]:
                html += f"""<tr>
<td>{srow.md:.2f}</td>
<td>{srow.inc:.2f}</td>
<td>{srow.azi:.2f}</td>
<td>{srow.tvd:.2f}</td>
<td>{srow.north:.2f}</td>
<td>{srow.east:.2f}</td>
<td>{srow.dls:.2f}</td>
</tr>"""
            html += "</table>"

        # Safety
        html += "<h1>9. Safety Summary</h1>"
        if safety_reports:
            html += """<table class="table">
<tr><th>Date</th><th>Days without LTI</th><th>Near Miss</th><th>Last Fire Drill</th><th>Last BOP Drill</th></tr>"""
            for sr in safety_reports:
                html += f"""<tr>
<td>{sr.report_date}</td>
<td>{sr.days_without_lti or 0}</td>
<td>{sr.near_miss_count or 0}</td>
<td>{sr.last_fire_drill or ''}</td>
<td>{sr.last_bop_drill or ''}</td>
</tr>"""
            html += "</table>"

        # Logistics
        html += "<h1>10. Logistics & Services</h1>"
        html += f"<p><b>Personnel:</b> {len(personnel)} | <b>Services:</b> {len(services)} | <b>Transport:</b> {len(data.get('transport', []))}</p>"

        # Cost
        html += "<h1>11. Cost Summary</h1>"
        if cost_records:
            html += """<table class="table">
<tr><th>Date</th><th>Category</th><th>Planned</th><th>Actual</th><th>Variance</th><th>Status</th></tr>"""
            for c in cost_records:
                variance = (c.planned_cost or 0) - (c.actual_cost or 0)
                html += f"""<tr>
<td>{c.cost_date or ''}</td>
<td>{c.category or ''}</td>
<td>{c.planned_cost or 0:.2f}</td>
<td>{c.actual_cost or 0:.2f}</td>
<td>{variance:.2f}</td>
<td>{c.status or ''}</td>
</tr>"""
            html += "</table>"
        else:
            html += f"<p>Total Estimated Cost: ${s.get('total_cost', 0):,.0f}</p>"

        # Footer
        html += f"""
<div class="footer">
{bc.footer_text} | EOWR | {datetime.now().strftime("%Y-%m-%d %H:%M")} | {well_name}
</div>
</body></html>
"""
        return html

    def _save_pdf(self, html: str, output_path: str) -> bool:
        try:
            printer = QPrinter(QPrinter.HighResolution)
            printer.setOutputFormat(QPrinter.PdfFormat)
            printer.setOutputFileName(output_path)
            printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
            printer.setPageMargins(QMarginsF(10, 10, 10, 10), QPageLayout.Unit.Millimeter)

            doc = QTextDocument()
            doc.setHtml(html)
            doc.print_(printer)
            return True
        except Exception as e:
            logger.error(f"EOWR PDF save error: {e}")
            return False

    def _save_html(self, html: str, output_path: str) -> bool:
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html)
            return True
        except Exception as e:
            logger.error(f"EOWR HTML save error: {e}")
            return False

    def _save_excel(self, data: dict, output_path: str,
                    selected_sections=None) -> bool:
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill

            wb = Workbook()
            wb.remove(wb.active)

            header_font = Font(bold=True, color="FFFFFF")
            header_fill = PatternFill("solid", fgColor="2C3E50")

            # Summary sheet
            ws = wb.create_sheet("Summary")
            ws["A1"] = "END OF WELL REPORT"
            ws["A2"] = data["well"].get("name", "")
            ws["A4"] = "Metric"
            ws["B4"] = "Value"
            ws["A4"].font = header_font
            ws["A4"].fill = header_fill
            ws["B4"].font = header_font
            ws["B4"].fill = header_fill

            metrics = [
                ("Total Reports", data["summary"].get("total_reports", 0)),
                ("Final Depth", data["summary"].get("final_depth", 0)),
                ("Average ROP", data["summary"].get("avg_rop", 0)),
                ("Total NPT", data["summary"].get("total_npt", 0)),
                ("NPT %", data["summary"].get("npt_pct", 0)),
                ("Total Cost", data["summary"].get("total_cost", 0)),
            ]
            for i, (k, v) in enumerate(metrics, 5):
                ws.cell(row=i, column=1, value=k)
                ws.cell(row=i, column=2, value=str(v))

            # Sections
            self._write_sheet_from_objects(
                wb, "Sections", data.get("sections", [])
            )
            self._write_sheet_from_objects(
                wb, "DailyReports", data.get("daily_reports", [])
            )
            self._write_sheet_from_objects(
                wb, "DrillingParams", data.get("drilling_params", [])
            )
            self._write_sheet_from_objects(
                wb, "MudReports", data.get("mud_reports", [])
            )
            self._write_sheet_from_objects(
                wb, "Surveys", data.get("surveys", [])
            )
            self._write_sheet_from_objects(
                wb, "Safety", data.get("safety_reports", [])
            )
            self._write_sheet_from_objects(
                wb, "Cost", data.get("cost_records", [])
            )

            wb.save(output_path)
            return True
        except Exception as e:
            logger.error(f"EOWR Excel save error: {e}")
            return False

    def _write_sheet_from_objects(self, wb, sheet_name, objects):
        """نوشتن لیست آبجکت ORM در شیت اکسل"""
        if not objects:
            return
        ws = wb.create_sheet(sheet_name[:31])

        # headers
        cols = list(objects[0].__table__.columns.keys())
        for c, h in enumerate(cols, 1):
            ws.cell(row=1, column=c, value=h)

        for r, obj in enumerate(objects, 2):
            for c, h in enumerate(cols, 1):
                ws.cell(row=r, column=c, value=str(getattr(obj, h, "")))
                
class NPTReportEngine:
    """موتور تولید NPT Summary Report حرفه‌ای"""

    def __init__(self, db_manager):
        self.db = db_manager
        self.branding = ReportBranding()

    def generate(self, well_id: int, output_path: str,
                 format: str = "pdf",
                 from_date=None, to_date=None) -> bool:
        try:
            data = self._collect_data(well_id, from_date, to_date)
            if not data:
                return False
            html = self._build_html(data)
            if format == "pdf":
                return self._save_pdf(html, output_path)
            elif format == "html":
                return self._save_html(html, output_path)
            elif format == "excel":
                return self._save_excel(data, output_path)
            return False
        except Exception as e:
            logger.error(f"NPT report error: {e}")
            return False

    def _collect_data(self, well_id, from_date=None, to_date=None):
        from core.database import TimeLog24H, DailyReport
        session = self.db.create_session()
        try:
            well = self.db.get_well_by_id(well_id) or {}

            query = session.query(TimeLog24H, DailyReport).join(
                DailyReport, TimeLog24H.report_id == DailyReport.id
            ).filter(
                DailyReport.well_id == well_id,
                TimeLog24H.is_npt == True
            )
            if from_date:
                query = query.filter(DailyReport.report_date >= from_date)
            if to_date:
                query = query.filter(DailyReport.report_date <= to_date)

            npt_logs = query.order_by(
                DailyReport.report_date, TimeLog24H.time_from
            ).all()

            # All logs for total hours
            total_query = session.query(func.sum(TimeLog24H.duration)).join(
                DailyReport, TimeLog24H.report_id == DailyReport.id
            ).filter(DailyReport.well_id == well_id)
            if from_date:
                total_query = total_query.filter(DailyReport.report_date >= from_date)
            if to_date:
                total_query = total_query.filter(DailyReport.report_date <= to_date)
            total_hours = total_query.scalar() or 1

            # Aggregations
            by_main_code = {}
            by_sub_code = {}
            by_contractor = {}
            by_phase = {}
            by_date = {}
            entries = []
            total_npt = 0

            for log, rep in npt_logs:
                hrs = log.duration or 0
                total_npt += hrs
                mc = log.main_code or "Unknown"
                sc = log.sub_code or ""
                cont = log.contractor or "Unknown"
                phase = log.main_phase or "Unknown"
                rd = str(rep.report_date)

                by_main_code[mc] = by_main_code.get(mc, 0) + hrs
                key_sub = f"{mc} → {sc}" if sc else mc
                by_sub_code[key_sub] = by_sub_code.get(key_sub, 0) + hrs
                by_contractor[cont] = by_contractor.get(cont, 0) + hrs
                by_phase[phase] = by_phase.get(phase, 0) + hrs
                by_date[rd] = by_date.get(rd, 0) + hrs

                entries.append({
                    "date": rd,
                    "from": log.time_from.strftime("%H:%M") if log.time_from else "",
                    "to": log.time_to.strftime("%H:%M") if log.time_to else "",
                    "hours": hrs,
                    "main_code": mc,
                    "sub_code": sc,
                    "contractor": cont,
                    "phase": phase,
                    "description": log.activity_description or "",
                })

            # Total reports
            report_count = session.query(DailyReport).filter(
                DailyReport.well_id == well_id
            ).count()

            npt_pct = (total_npt / total_hours * 100) if total_hours > 0 else 0
            daily_avg = total_npt / report_count if report_count > 0 else 0

            # Cost estimate
            daily_rate = 60000
            npt_cost = (total_npt / 24) * daily_rate

            return {
                "well": well,
                "entries": entries,
                "by_main_code": dict(sorted(by_main_code.items(), key=lambda x: x[1], reverse=True)),
                "by_sub_code": dict(sorted(by_sub_code.items(), key=lambda x: x[1], reverse=True)),
                "by_contractor": dict(sorted(by_contractor.items(), key=lambda x: x[1], reverse=True)),
                "by_phase": dict(sorted(by_phase.items(), key=lambda x: x[1], reverse=True)),
                "by_date": dict(sorted(by_date.items())),
                "total_npt": total_npt,
                "total_hours": total_hours,
                "npt_pct": npt_pct,
                "daily_avg": daily_avg,
                "npt_cost": npt_cost,
                "report_count": report_count,
                "from_date": str(from_date or "Start"),
                "to_date": str(to_date or "End"),
            }
        except Exception as e:
            logger.error(f"NPT collect error: {e}")
            return None
        finally:
            session.close()

    def _build_html(self, data):
        w = data["well"]
        bc = self.branding
        well_name = w.get("name", "Unknown")
        total_npt = data["total_npt"]
        npt_pct = data["npt_pct"]
        daily_avg = data["daily_avg"]
        npt_cost = data["npt_cost"]

        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
@page {{ margin: 15mm; }}
body {{ font-family: Arial; font-size: 9pt; color: #2c3e50; }}
h1 {{ color: {bc.primary_color}; border-bottom: 3px solid #e74c3c; padding-bottom: 8px; font-size: 16pt; }}
h2 {{ color: #e74c3c; border-bottom: 1px solid #fadbd8; margin-top: 15px; font-size: 12pt; }}
.kpi-row {{ margin: 10px 0; }}
.kpi-box {{
    display: inline-block; width: 22%; margin: 4px;
    padding: 10px; border-radius: 4px;
    vertical-align: top; text-align: center;
}}
.kpi-red {{ background: #fadbd8; border-left: 4px solid #e74c3c; }}
.kpi-orange {{ background: #fef9e7; border-left: 4px solid #f39c12; }}
.kpi-blue {{ background: #eaf2f8; border-left: 4px solid #3498db; }}
.kpi-green {{ background: #eafaf1; border-left: 4px solid #27ae60; }}
.kpi-value {{ font-size: 20pt; font-weight: bold; }}
.kpi-label {{ font-size: 8pt; color: #666; }}
.table {{ width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 8pt; }}
.table th {{ background: {bc.primary_color}; color: white; padding: 5px; border: 1px solid #ccc; }}
.table td {{ padding: 4px 5px; border: 1px solid #ddd; }}
.table tr:nth-child(even) {{ background: #f8f9fa; }}
.bar-container {{ width: 100%; background: #ecf0f1; border-radius: 3px; height: 20px; margin: 2px 0; }}
.bar-fill {{ height: 100%; border-radius: 3px; min-width: 2px; }}
.bar-red {{ background: #e74c3c; }}
.bar-orange {{ background: #f39c12; }}
.bar-blue {{ background: #3498db; }}
.footer {{ margin-top: 15px; font-size: 7pt; color: #999; text-align: center; border-top: 1px solid #ccc; padding-top: 5px; }}
.page-break {{ page-break-before: always; }}
</style></head><body>

<h1>⏱️ NPT SUMMARY REPORT</h1>
<p><b>Well:</b> {well_name} | <b>Period:</b> {data["from_date"]} to {data["to_date"]} | <b>Reports:</b> {data["report_count"]}</p>

<div class="kpi-row">
    <div class="kpi-box kpi-red">
        <div class="kpi-value">{total_npt:.1f}</div>
        <div class="kpi-label">Total NPT (hours)</div>
    </div>
    <div class="kpi-box kpi-orange">
        <div class="kpi-value">{npt_pct:.1f}%</div>
        <div class="kpi-label">NPT Percentage</div>
    </div>
    <div class="kpi-box kpi-blue">
        <div class="kpi-value">{daily_avg:.1f}</div>
        <div class="kpi-label">Daily Average (hrs/day)</div>
    </div>
    <div class="kpi-box kpi-green">
        <div class="kpi-value">${npt_cost:,.0f}</div>
        <div class="kpi-label">Estimated NPT Cost</div>
    </div>
</div>
"""

        # By Main Code
        html += "<h2>📊 NPT by Main Code</h2>"
        html += self._build_breakdown_table(
            data["by_main_code"], total_npt, "bar-red"
        )

        # By Sub Code
        html += "<h2>📊 NPT by Sub Code (Top 15)</h2>"
        top_sub = dict(list(data["by_sub_code"].items())[:15])
        html += self._build_breakdown_table(
            top_sub, total_npt, "bar-orange"
        )

        # By Contractor
        html += "<h2>🏢 NPT by Contractor</h2>"
        html += self._build_breakdown_table(
            data["by_contractor"], total_npt, "bar-blue"
        )

        # By Phase
        html += "<h2>📋 NPT by Phase</h2>"
        html += self._build_breakdown_table(
            data["by_phase"], total_npt, "bar-red"
        )

        # Daily Trend
        html += '<div class="page-break"></div>'
        html += "<h2>📅 NPT Daily Trend</h2>"
        html += """<table class="table">
<tr><th>Date</th><th>NPT Hours</th><th>Distribution</th></tr>"""
        max_daily = max(data["by_date"].values()) if data["by_date"] else 1
        for dt, hrs in data["by_date"].items():
            pct = (hrs / max_daily * 100) if max_daily > 0 else 0
            html += f"""<tr>
<td>{dt}</td>
<td style="text-align:right"><b>{hrs:.1f}</b></td>
<td><div class="bar-container"><div class="bar-fill bar-red" style="width:{pct:.0f}%"></div></div></td>
</tr>"""
        html += "</table>"

        # Event Details
        html += "<h2>📋 NPT Event Details</h2>"
        html += """<table class="table">
<tr><th>Date</th><th>From</th><th>To</th><th>Hours</th><th>Code</th><th>Sub Code</th><th>Contractor</th><th>Description</th></tr>"""
        for e in data["entries"]:
            desc = wrap_html(e["description"], 150)
            html += f"""<tr>
<td>{e["date"]}</td>
<td>{e["from"]}</td>
<td>{e["to"]}</td>
<td style="text-align:right"><b>{e["hours"]:.2f}</b></td>
<td>{e["main_code"]}</td>
<td>{e["sub_code"]}</td>
<td>{e["contractor"]}</td>
<td>{desc}</td>
</tr>"""
        html += "</table>"

        html += f"""
<div class="footer">
{bc.footer_text} | NPT Summary | {datetime.now().strftime("%Y-%m-%d %H:%M")} | {well_name}
</div></body></html>"""

        return html

    def _build_breakdown_table(self, breakdown, total, bar_class):
        """ساخت جدول breakdown با bar chart"""
        html = """<table class="table">
<tr><th>Category</th><th style="width:70px">Hours</th><th style="width:50px">%</th><th>Distribution</th></tr>"""
        for cat, hrs in breakdown.items():
            pct = (hrs / total * 100) if total > 0 else 0
            html += f"""<tr>
<td>{cat}</td>
<td style="text-align:right"><b>{hrs:.1f}</b></td>
<td style="text-align:right">{pct:.1f}%</td>
<td><div class="bar-container"><div class="bar-fill {bar_class}" style="width:{pct:.0f}%"></div></div></td>
</tr>"""
        html += f"""<tr style="font-weight:bold;background:#ecf0f1">
<td>TOTAL</td><td style="text-align:right">{total:.1f}</td><td>100%</td><td></td>
</tr></table>"""
        return html

    def _save_pdf(self, html, path):
        try:
            printer = QPrinter(QPrinter.HighResolution)
            printer.setOutputFormat(QPrinter.PdfFormat)
            printer.setOutputFileName(path)
            printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
            printer.setPageMargins(QMarginsF(10, 10, 10, 10), QPageLayout.Unit.Millimeter)
            doc = QTextDocument()
            doc.setHtml(html)
            doc.print_(printer)
            return True
        except Exception as e:
            logger.error(f"NPT PDF error: {e}")
            return False

    def _save_html(self, html, path):
        try:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(html)
            return True
        except Exception as e:
            logger.error(f"NPT HTML error: {e}")
            return False

    def _save_excel(self, data, path):
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill
            wb = Workbook()
            hf = Font(bold=True, color="FFFFFF")
            hfill = PatternFill("solid", fgColor="2C3E50")

            # Summary
            ws = wb.active
            ws.title = "NPT Summary"
            summary = [
                ("Metric", "Value"),
                ("Total NPT (hrs)", data["total_npt"]),
                ("NPT %", data["npt_pct"]),
                ("Daily Average", data["daily_avg"]),
                ("NPT Cost ($)", data["npt_cost"]),
                ("Total Reports", data["report_count"]),
            ]
            for i, (k, v) in enumerate(summary, 1):
                ws.cell(row=i, column=1, value=k)
                ws.cell(row=i, column=2, value=str(round(v, 2) if isinstance(v, float) else v))
                if i == 1:
                    ws.cell(row=1, column=1).font = hf
                    ws.cell(row=1, column=1).fill = hfill
                    ws.cell(row=1, column=2).font = hf
                    ws.cell(row=1, column=2).fill = hfill

            # By Main Code
            ws2 = wb.create_sheet("By Main Code")
            ws2.cell(row=1, column=1, value="Code").font = hf
            ws2.cell(row=1, column=1).fill = hfill
            ws2.cell(row=1, column=2, value="Hours").font = hf
            ws2.cell(row=1, column=2).fill = hfill
            ws2.cell(row=1, column=3, value="%").font = hf
            ws2.cell(row=1, column=3).fill = hfill
            for i, (k, v) in enumerate(data["by_main_code"].items(), 2):
                ws2.cell(row=i, column=1, value=k)
                ws2.cell(row=i, column=2, value=round(v, 2))
                ws2.cell(row=i, column=3, value=round(v / data["total_npt"] * 100, 1) if data["total_npt"] > 0 else 0)

            # By Contractor
            ws3 = wb.create_sheet("By Contractor")
            ws3.cell(row=1, column=1, value="Contractor").font = hf
            ws3.cell(row=1, column=1).fill = hfill
            ws3.cell(row=1, column=2, value="Hours").font = hf
            ws3.cell(row=1, column=2).fill = hfill
            for i, (k, v) in enumerate(data["by_contractor"].items(), 2):
                ws3.cell(row=i, column=1, value=k)
                ws3.cell(row=i, column=2, value=round(v, 2))

            # Events
            ws4 = wb.create_sheet("NPT Events")
            headers = ["Date", "From", "To", "Hours", "Code", "Sub Code", "Contractor", "Description"]
            for c, h in enumerate(headers, 1):
                ws4.cell(row=1, column=c, value=h).font = hf
                ws4.cell(row=1, column=c).fill = hfill
            for i, e in enumerate(data["entries"], 2):
                ws4.cell(row=i, column=1, value=e["date"])
                ws4.cell(row=i, column=2, value=e["from"])
                ws4.cell(row=i, column=3, value=e["to"])
                ws4.cell(row=i, column=4, value=round(e["hours"], 2))
                ws4.cell(row=i, column=5, value=e["main_code"])
                ws4.cell(row=i, column=6, value=e["sub_code"])
                ws4.cell(row=i, column=7, value=e["contractor"])
                ws4.cell(row=i, column=8, value=e["description"][:200])

            # Daily
            ws5 = wb.create_sheet("Daily Trend")
            ws5.cell(row=1, column=1, value="Date").font = hf
            ws5.cell(row=1, column=1).fill = hfill
            ws5.cell(row=1, column=2, value="NPT Hours").font = hf
            ws5.cell(row=1, column=2).fill = hfill
            for i, (k, v) in enumerate(data["by_date"].items(), 2):
                ws5.cell(row=i, column=1, value=k)
                ws5.cell(row=i, column=2, value=round(v, 2))

            wb.save(path)
            return True
        except Exception as e:
            logger.error(f"NPT Excel error: {e}")
            return False
            
class CostReportEngine:
    """موتور تولید Cost Report حرفه‌ای"""

    def __init__(self, db_manager):
        self.db = db_manager
        self.branding = ReportBranding()

    def generate(self, well_id: int, output_path: str,
                 format: str = "pdf",
                 daily_rate: float = 45000,
                 spread_rate: float = 15000) -> bool:
        try:
            data = self._collect_data(well_id, daily_rate, spread_rate)
            if not data:
                return False
            html = self._build_html(data)
            if format == "pdf":
                return self._save_pdf(html, output_path)
            elif format == "html":
                return self._save_html(html, output_path)
            elif format == "excel":
                return self._save_excel(data, output_path)
            return False
        except Exception as e:
            logger.error(f"Cost report error: {e}")
            return False

    def _collect_data(self, well_id, daily_rate, spread_rate):
        from core.database import DailyReport, TimeLog24H
        session = self.db.create_session()
        try:
            well = self.db.get_well_by_id(well_id) or {}
            reports = session.query(DailyReport).filter(
                DailyReport.well_id == well_id
            ).order_by(DailyReport.report_date).all()

            total_days = len(reports)
            total_daily_cost = daily_rate + spread_rate

            # NPT
            total_npt = session.query(func.sum(TimeLog24H.duration)).join(
                DailyReport, TimeLog24H.report_id == DailyReport.id
            ).filter(
                DailyReport.well_id == well_id,
                TimeLog24H.is_npt == True
            ).scalar() or 0
            npt_days = total_npt / 24

            total_cost = total_days * total_daily_cost
            npt_cost = npt_days * total_daily_cost
            pt_cost = total_cost - npt_cost

            max_depth = max(
                [(r.depth_2400 or 0) for r in reports], default=0
            )
            cost_per_meter = total_cost / max_depth if max_depth > 0 else 0
            cost_per_foot = cost_per_meter / 3.28084 if max_depth > 0 else 0

            # Cumulative
            cum_data = []
            cum_cost = 0
            for r in reports:
                cum_cost += total_daily_cost
                cum_data.append({
                    "date": str(r.report_date),
                    "rig_day": r.rig_day or 0,
                    "depth": r.depth_2400 or 0,
                    "daily_cost": total_daily_cost,
                    "cum_cost": cum_cost,
                })

            # Cost records from DB
            try:
                from core.database import CostRecord
                cost_records = session.query(CostRecord).filter(
                    CostRecord.well_id == well_id
                ).order_by(CostRecord.category).all()
                categories = {}
                for cr in cost_records:
                    cat = cr.category or "Other"
                    if cat not in categories:
                        categories[cat] = {"planned": 0, "actual": 0}
                    categories[cat]["planned"] += cr.planned_cost or 0
                    categories[cat]["actual"] += cr.actual_cost or 0
            except Exception:
                cost_records = []
                categories = {}

            return {
                "well": well,
                "total_days": total_days,
                "daily_rate": daily_rate,
                "spread_rate": spread_rate,
                "total_daily_cost": total_daily_cost,
                "total_cost": total_cost,
                "npt_cost": npt_cost,
                "pt_cost": pt_cost,
                "npt_days": npt_days,
                "max_depth": max_depth,
                "cost_per_meter": cost_per_meter,
                "cost_per_foot": cost_per_foot,
                "cumulative": cum_data,
                "categories": categories,
            }
        except Exception as e:
            logger.error(f"Cost collect error: {e}")
            return None
        finally:
            session.close()

    def _build_html(self, data):
        w = data["well"]
        bc = self.branding
        well_name = w.get("name", "Unknown")

        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
@page {{ margin: 15mm; }}
body {{ font-family: Arial; font-size: 9pt; color: #2c3e50; }}
h1 {{ color: {bc.primary_color}; border-bottom: 3px solid #27ae60; padding-bottom: 8px; font-size: 16pt; }}
h2 {{ color: #27ae60; border-bottom: 1px solid #d5f5e3; margin-top: 15px; font-size: 12pt; }}
.kpi-row {{ margin: 10px 0; }}
.kpi-box {{
    display: inline-block; width: 22%; margin: 4px;
    padding: 10px; border-radius: 4px;
    vertical-align: top; text-align: center;
}}
.kpi-value {{ font-size: 18pt; font-weight: bold; }}
.kpi-label {{ font-size: 8pt; color: #666; }}
.table {{ width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 8pt; }}
.table th {{ background: {bc.primary_color}; color: white; padding: 5px; border: 1px solid #ccc; }}
.table td {{ padding: 4px 5px; border: 1px solid #ddd; }}
.table tr:nth-child(even) {{ background: #f8f9fa; }}
.footer {{ margin-top: 15px; font-size: 7pt; color: #999; text-align: center; border-top: 1px solid #ccc; padding-top: 5px; }}
</style></head><body>

<h1>💰 COST ANALYSIS REPORT</h1>
<p><b>Well:</b> {well_name} | <b>Total Days:</b> {data["total_days"]} | <b>Final Depth:</b> {data["max_depth"]:.0f} m</p>

<div class="kpi-row">
    <div class="kpi-box" style="background:#eafaf1;border-left:4px solid #27ae60">
        <div class="kpi-value" style="color:#27ae60">${data["total_cost"]:,.0f}</div>
        <div class="kpi-label">Total Well Cost</div>
    </div>
    <div class="kpi-box" style="background:#fadbd8;border-left:4px solid #e74c3c">
        <div class="kpi-value" style="color:#e74c3c">${data["npt_cost"]:,.0f}</div>
        <div class="kpi-label">NPT Cost ({data["npt_days"]:.1f} days)</div>
    </div>
    <div class="kpi-box" style="background:#eaf2f8;border-left:4px solid #3498db">
        <div class="kpi-value" style="color:#3498db">${data["cost_per_meter"]:,.0f}</div>
        <div class="kpi-label">Cost per Meter</div>
    </div>
    <div class="kpi-box" style="background:#fef9e7;border-left:4px solid #f39c12">
        <div class="kpi-value" style="color:#f39c12">${data["total_daily_cost"]:,.0f}</div>
        <div class="kpi-label">Daily Cost (Rig + Spread)</div>
    </div>
</div>

<h2>📊 Cost Parameters</h2>
<table class="table">
<tr><th>Parameter</th><th>Value</th><th>Parameter</th><th>Value</th></tr>
<tr><td>Rig Day Rate</td><td>${data["daily_rate"]:,.0f}/day</td><td>Spread Cost</td><td>${data["spread_rate"]:,.0f}/day</td></tr>
<tr><td>Total Days</td><td>{data["total_days"]}</td><td>NPT Days</td><td>{data["npt_days"]:.1f}</td></tr>
<tr><td>Productive Cost</td><td>${data["pt_cost"]:,.0f}</td><td>NPT Cost</td><td>${data["npt_cost"]:,.0f}</td></tr>
<tr><td>Cost/Meter</td><td>${data["cost_per_meter"]:,.0f}</td><td>Cost/Foot</td><td>${data["cost_per_foot"]:,.0f}</td></tr>
</table>
"""

        # Categories
        if data["categories"]:
            html += "<h2>📋 Cost by Category</h2>"
            html += """<table class="table">
<tr><th>Category</th><th>Planned ($)</th><th>Actual ($)</th><th>Variance ($)</th><th>Status</th></tr>"""
            total_p = total_a = 0
            for cat, vals in data["categories"].items():
                p = vals["planned"]
                a = vals["actual"]
                v = p - a
                total_p += p
                total_a += a
                color = "#27ae60" if v >= 0 else "#e74c3c"
                html += f"""<tr>
<td>{cat}</td>
<td style="text-align:right">{p:,.0f}</td>
<td style="text-align:right">{a:,.0f}</td>
<td style="text-align:right;color:{color}"><b>{v:,.0f}</b></td>
<td>{'✅ Under' if v >= 0 else '❌ Over'}</td>
</tr>"""
            html += f"""<tr style="font-weight:bold;background:#ecf0f1">
<td>TOTAL</td><td style="text-align:right">{total_p:,.0f}</td>
<td style="text-align:right">{total_a:,.0f}</td>
<td style="text-align:right">{total_p-total_a:,.0f}</td><td></td>
</tr></table>"""

        # Cumulative Cost Table
        html += "<h2>📈 Cumulative Cost vs Depth</h2>"
        html += """<table class="table">
<tr><th>Day</th><th>Date</th><th>Depth (m)</th><th>Daily Cost ($)</th><th>Cumulative ($)</th></tr>"""
        for c in data["cumulative"]:
            html += f"""<tr>
<td>{c["rig_day"]}</td><td>{c["date"]}</td>
<td>{c["depth"]:.0f}</td>
<td style="text-align:right">{c["daily_cost"]:,.0f}</td>
<td style="text-align:right"><b>{c["cum_cost"]:,.0f}</b></td>
</tr>"""
        html += "</table>"

        html += f"""
<div class="footer">
{bc.footer_text} | Cost Report | {datetime.now().strftime("%Y-%m-%d %H:%M")} | {well_name}
</div></body></html>"""
        return html

    def _save_pdf(self, html, path):
        try:
            printer = QPrinter(QPrinter.HighResolution)
            printer.setOutputFormat(QPrinter.PdfFormat)
            printer.setOutputFileName(path)
            printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
            printer.setPageMargins(QMarginsF(10, 10, 10, 10), QPageLayout.Unit.Millimeter)
            doc = QTextDocument()
            doc.setHtml(html)
            doc.print_(printer)
            return True
        except Exception as e:
            logger.error(f"Cost PDF error: {e}")
            return False

    def _save_html(self, html, path):
        try:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(html)
            return True
        except: return False

    def _save_excel(self, data, path):
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill
            wb = Workbook()
            hf = Font(bold=True, color="FFFFFF")
            hfill = PatternFill("solid", fgColor="2C3E50")

            ws = wb.active
            ws.title = "Cost Summary"
            rows = [
                ("Metric", "Value"),
                ("Total Cost", f"${data['total_cost']:,.0f}"),
                ("NPT Cost", f"${data['npt_cost']:,.0f}"),
                ("Productive Cost", f"${data['pt_cost']:,.0f}"),
                ("Cost/Meter", f"${data['cost_per_meter']:,.0f}"),
                ("Cost/Foot", f"${data['cost_per_foot']:,.0f}"),
                ("Total Days", str(data['total_days'])),
                ("NPT Days", f"{data['npt_days']:.1f}"),
            ]
            for i, (k, v) in enumerate(rows, 1):
                ws.cell(row=i, column=1, value=k)
                ws.cell(row=i, column=2, value=v)
                if i == 1:
                    ws.cell(row=1, column=1).font = hf
                    ws.cell(row=1, column=1).fill = hfill
                    ws.cell(row=1, column=2).font = hf
                    ws.cell(row=1, column=2).fill = hfill

            # Cumulative
            ws2 = wb.create_sheet("Cumulative")
            for c, h in enumerate(["Day", "Date", "Depth", "Daily Cost", "Cumulative"], 1):
                ws2.cell(row=1, column=c, value=h).font = hf
                ws2.cell(row=1, column=c).fill = hfill
            for i, c in enumerate(data["cumulative"], 2):
                ws2.cell(row=i, column=1, value=c["rig_day"])
                ws2.cell(row=i, column=2, value=c["date"])
                ws2.cell(row=i, column=3, value=c["depth"])
                ws2.cell(row=i, column=4, value=c["daily_cost"])
                ws2.cell(row=i, column=5, value=c["cum_cost"])

            # Categories
            if data["categories"]:
                ws3 = wb.create_sheet("Categories")
                for c, h in enumerate(["Category", "Planned", "Actual", "Variance"], 1):
                    ws3.cell(row=1, column=c, value=h).font = hf
                    ws3.cell(row=1, column=c).fill = hfill
                for i, (cat, vals) in enumerate(data["categories"].items(), 2):
                    ws3.cell(row=i, column=1, value=cat)
                    ws3.cell(row=i, column=2, value=vals["planned"])
                    ws3.cell(row=i, column=3, value=vals["actual"])
                    ws3.cell(row=i, column=4, value=vals["planned"] - vals["actual"])

            wb.save(path)
            return True
        except Exception as e:
            logger.error(f"Cost Excel error: {e}")
            return False
            
class PlanReportEngine:
    """موتور تولید Drilling Plan Report حرفه‌ای"""

    def __init__(self, db_manager):
        self.db = db_manager
        self.branding = ReportBranding()

    def generate(self, well_id: int, output_path: str,
                 format: str = "pdf") -> bool:
        try:
            data = self._collect_data(well_id)
            if not data:
                return False
            html = self._build_html(data)
            if format == "pdf":
                return self._save_pdf(html, output_path)
            elif format == "html":
                return self._save_html(html, output_path)
            elif format == "excel":
                return self._save_excel(data, output_path)
            return False
        except Exception as e:
            logger.error(f"Plan report error: {e}")
            return False

    def _collect_data(self, well_id):
        from core.database import WellPlan, PlannedActivity, Well
        session = self.db.create_session()
        try:
            well = self.db.get_well_by_id(well_id) or {}
            plans = session.query(WellPlan).filter(
                WellPlan.well_id == well_id
            ).order_by(WellPlan.created_at.desc()).all()

            if not plans:
                return None

            active_plan = next((p for p in plans if p.is_active), plans[0])

            activities = session.query(PlannedActivity).filter(
                PlannedActivity.well_id == well_id,
                PlannedActivity.plan_id == active_plan.id
            ).order_by(PlannedActivity.planned_start).all()

            total_hrs = sum(a.planned_duration_hours or 0 for a in activities)
            total_days = total_hrs / 24
            max_depth = max(
                [a.planned_depth_to or 0 for a in activities],
                default=0
            )

            # breakdown by phase
            by_phase = {}
            for a in activities:
                phase = a.phase_code or "Unknown"
                by_phase[phase] = by_phase.get(phase, 0) + (
                    a.planned_duration_hours or 0
                )

            return {
                "well": well,
                "plan": active_plan,
                "all_plans": plans,
                "activities": activities,
                "total_hrs": total_hrs,
                "total_days": total_days,
                "max_depth": max_depth,
                "by_phase": dict(sorted(by_phase.items(), key=lambda x: x[1], reverse=True)),
            }
        except Exception as e:
            logger.error(f"Plan collect error: {e}")
            return None
        finally:
            session.close()

    def _build_html(self, data):
        w = data["well"]
        plan = data["plan"]
        acts = data["activities"]
        bc = self.branding

        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
@page {{ margin: 15mm; }}
body {{ font-family: Arial; font-size: 9pt; color: #2c3e50; }}
h1 {{ color: {bc.primary_color}; border-bottom: 3px solid #9b59b6; padding-bottom: 8px; font-size: 16pt; }}
h2 {{ color: #9b59b6; border-bottom: 1px solid #e8daef; margin-top: 15px; font-size: 12pt; }}
.kpi-box {{
    display: inline-block; width: 22%; margin: 4px;
    padding: 10px; border-radius: 4px; vertical-align: top; text-align: center;
    background: #f8f9fa; border-left: 4px solid #9b59b6;
}}
.kpi-value {{ font-size: 18pt; font-weight: bold; color: {bc.primary_color}; }}
.kpi-label {{ font-size: 8pt; color: #666; }}
.table {{ width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 8pt; }}
.table th {{ background: {bc.primary_color}; color: white; padding: 5px; border: 1px solid #ccc; }}
.table td {{ padding: 4px 5px; border: 1px solid #ddd; }}
.table tr:nth-child(even) {{ background: #f8f9fa; }}
.bar-container {{ width: 100%; background: #ecf0f1; border-radius: 3px; height: 18px; margin: 2px 0; }}
.bar-fill {{ height: 100%; background: #9b59b6; border-radius: 3px; min-width: 2px; }}
.footer {{ margin-top: 15px; font-size: 7pt; color: #999; text-align: center; border-top: 1px solid #ccc; padding-top: 5px; }}
</style></head><body>

<h1>📋 DRILLING PLAN REPORT</h1>
<p><b>Well:</b> {w.get("name","")} | <b>Plan:</b> {plan.plan_name} | <b>Version:</b> {plan.plan_version}</p>
<p><b>Planned Spud:</b> {plan.planned_spud_date or ''} | <b>Planned Finish:</b> {plan.planned_finish_date or ''}</p>

<div>
    <div class="kpi-box">
        <div class="kpi-value">{len(acts)}</div>
        <div class="kpi-label">Activities</div>
    </div>
    <div class="kpi-box">
        <div class="kpi-value">{data["total_days"]:.1f}</div>
        <div class="kpi-label">Planned Days</div>
    </div>
    <div class="kpi-box">
        <div class="kpi-value">{data["total_hrs"]:.1f}</div>
        <div class="kpi-label">Planned Hours</div>
    </div>
    <div class="kpi-box">
        <div class="kpi-value">{data["max_depth"]:.0f} m</div>
        <div class="kpi-label">Planned Final Depth</div>
    </div>
</div>
"""

        # Plan info
        html += "<h2>📝 Plan Information</h2>"
        html += f"<p><b>Description:</b><br>{(plan.description or '').replace(chr(10), '<br>')}</p>"

        # By phase
        html += "<h2>📊 Hours by Phase</h2>"
        total = data["total_hrs"] or 1
        html += """<table class="table">
<tr><th>Phase</th><th>Hours</th><th>%</th><th>Distribution</th></tr>"""
        for phase, hrs in data["by_phase"].items():
            pct = hrs / total * 100
            html += f"""<tr>
<td>{phase}</td>
<td style="text-align:right"><b>{hrs:.1f}</b></td>
<td style="text-align:right">{pct:.1f}%</td>
<td><div class="bar-container"><div class="bar-fill" style="width:{pct:.0f}%"></div></div></td>
</tr>"""
        html += "</table>"

        # Activities
        html += "<h2>📅 Activity Schedule</h2>"
        html += """<table class="table">
<tr><th>Phase</th><th>Activity</th><th>Depth From</th><th>Depth To</th><th>Duration (hrs)</th><th>Start</th><th>End</th></tr>"""
        for a in acts:
            html += f"""<tr>
<td>{a.phase_code or ''}</td>
<td>{a.activity_name or ''}</td>
<td>{a.planned_depth_from or 0:.0f}</td>
<td>{a.planned_depth_to or 0:.0f}</td>
<td>{a.planned_duration_hours or 0:.1f}</td>
<td>{a.planned_start.strftime('%Y-%m-%d %H:%M') if a.planned_start else ''}</td>
<td>{a.planned_end.strftime('%Y-%m-%d %H:%M') if a.planned_end else ''}</td>
</tr>"""
        html += "</table>"

        html += f"""
<div class="footer">
{bc.footer_text} | Plan Report | {datetime.now().strftime("%Y-%m-%d %H:%M")} | {w.get("name","")}
</div></body></html>"""
        return html

    def _save_pdf(self, html, path):
        try:
            printer = QPrinter(QPrinter.HighResolution)
            printer.setOutputFormat(QPrinter.PdfFormat)
            printer.setOutputFileName(path)
            printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
            printer.setPageMargins(QMarginsF(10, 10, 10, 10), QPageLayout.Unit.Millimeter)
            doc = QTextDocument()
            doc.setHtml(html)
            doc.print_(printer)
            return True
        except Exception as e:
            logger.error(f"Plan PDF error: {e}")
            return False

    def _save_html(self, html, path):
        try:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(html)
            return True
        except: return False

    def _save_excel(self, data, path):
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill
            wb = Workbook()
            hf = Font(bold=True, color="FFFFFF")
            hfill = PatternFill("solid", fgColor="2C3E50")

            ws = wb.active
            ws.title = "Plan Summary"
            rows = [
                ("Metric", "Value"),
                ("Plan Name", data["plan"].plan_name),
                ("Version", data["plan"].plan_version),
                ("Planned Days", data["total_days"]),
                ("Planned Hours", data["total_hrs"]),
                ("Planned Final Depth", data["max_depth"]),
                ("Activities", len(data["activities"])),
            ]
            for i, (k, v) in enumerate(rows, 1):
                ws.cell(row=i, column=1, value=k)
                ws.cell(row=i, column=2, value=str(v))
                if i == 1:
                    ws.cell(row=1, column=1).font = hf
                    ws.cell(row=1, column=1).fill = hfill
                    ws.cell(row=1, column=2).font = hf
                    ws.cell(row=1, column=2).fill = hfill

            # Activities
            ws2 = wb.create_sheet("Activities")
            headers = ["Phase", "Activity", "Depth From", "Depth To", "Duration (hrs)", "Start", "End"]
            for c, h in enumerate(headers, 1):
                ws2.cell(row=1, column=c, value=h).font = hf
                ws2.cell(row=1, column=c).fill = hfill
            for i, a in enumerate(data["activities"], 2):
                ws2.cell(row=i, column=1, value=a.phase_code or "")
                ws2.cell(row=i, column=2, value=a.activity_name or "")
                ws2.cell(row=i, column=3, value=a.planned_depth_from or 0)
                ws2.cell(row=i, column=4, value=a.planned_depth_to or 0)
                ws2.cell(row=i, column=5, value=a.planned_duration_hours or 0)
                ws2.cell(row=i, column=6, value=str(a.planned_start or ""))
                ws2.cell(row=i, column=7, value=str(a.planned_end or ""))

            wb.save(path)
            return True
        except Exception as e:
            logger.error(f"Plan Excel error: {e}")
            return False